name: End-to-end tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    env:
      MONGODB_URI: mongodb://localhost:27017/WalletAPI
      PORT: ${{vars.PORT}}
    services:
      mongo:
        image: mongo:6
        ports:
          - 27017:27017
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci
      
      - name: Start server & wait
        run: 
          npm start &
          npx wait-on http://127.0.0.1:3000/api/users
        
      - name: Cypress run
        uses: cypress-io/github-action@v6
      
    
