name: End-to-end tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci
      
        
        
      - name: Start server
        run: npm start &
        # Or: npm run dev &
        # The "&" keeps it running in background
      - name: Install Chrome deps
        run: sudo apt-get update && sudo apt-get install -y \xvfb libgtk-3-0 libnss3 libasound2
        
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome   # optional
          config-file: cypress.config.js
          headless: true
