name: End-to-end tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci
      
      - name: Start server and run
        run: npx start-server-and-test "npm run dev" http://localhost:3000 "npx cypress run"
        # Or: npm run dev &
        # The "&" keeps it running in background
        
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome   # optional
          config-file: cypress.config.js
    
